# Generated by Django 4.2.1 on 2023-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirPollution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60, verbose_name='Country')),
                ('city', models.CharField(max_length=90, verbose_name='City')),
                ('aqiValue', models.IntegerField(verbose_name='AQI Value')),
                ('aqiCategory', models.CharField(max_length=20, verbose_name='AQI Category')),
                ('coAQIValue', models.IntegerField(verbose_name='CO AQI Value')),
                ('coAQICategory', models.CharField(max_length=20, verbose_name='CO AQI Category')),
                ('ozoneAQIValue', models.IntegerField(verbose_name='Ozone AQI Value')),
                ('ozoneAQICategory', models.CharField(max_length=20, verbose_name='Ozone AQI Category')),
                ('no2AQIValue', models.IntegerField(verbose_name='NO2 AQI Value')),
                ('no2AQICategory', models.CharField(max_length=20, verbose_name='NO2 AQI Category')),
                ('pm2dot5AQIValue', models.IntegerField(verbose_name='PM2.5 AQI Value')),
                ('pm2dot5AQICategory', models.CharField(max_length=20, verbose_name='PM2.5 AQI Category')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('lng', models.FloatField(verbose_name='lng')),
            ],
        ),
    ]
