# Generated by Django 4.2.1 on 2023-05-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airpollution',
            old_name='aqiValue',
            new_name='aqivalue',
        ),
    ]
