# Generated by Django 4.2.1 on 2023-05-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_aqivalue_airpollution_aqivalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airpollution',
            old_name='aqiCategory',
            new_name='aqicategory',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='coAQICategory',
            new_name='coaqicategory',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='coAQIValue',
            new_name='coaqivalue',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='no2AQICategory',
            new_name='notwoaqicategory',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='no2AQIValue',
            new_name='notwoaqivalue',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='ozoneAQICategory',
            new_name='ozoneaqicategory',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='ozoneAQIValue',
            new_name='ozoneaqivalue',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='pm2dot5AQICategory',
            new_name='pmtwodotfivecategory',
        ),
        migrations.RenameField(
            model_name='airpollution',
            old_name='pm2dot5AQIValue',
            new_name='pmtwodotfivevalue',
        ),
    ]
