# Generated by Django 4.2.1 on 2023-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_aqicategory_airpollution_aqicategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpollution',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='airpollution',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='lng'),
        ),
    ]
