# Generated by Django 4.2.1 on 2023-05-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_airpollution_lat_alter_airpollution_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpollution',
            name='aqicategory',
            field=models.CharField(max_length=60, verbose_name='AQI Category'),
        ),
        migrations.AlterField(
            model_name='airpollution',
            name='coaqicategory',
            field=models.CharField(max_length=60, verbose_name='CO AQI Category'),
        ),
        migrations.AlterField(
            model_name='airpollution',
            name='notwoaqicategory',
            field=models.CharField(max_length=60, verbose_name='NO2 AQI Category'),
        ),
        migrations.AlterField(
            model_name='airpollution',
            name='ozoneaqicategory',
            field=models.CharField(max_length=60, verbose_name='Ozone AQI Category'),
        ),
        migrations.AlterField(
            model_name='airpollution',
            name='pmtwodotfivecategory',
            field=models.CharField(max_length=60, verbose_name='PM2.5 AQI Category'),
        ),
    ]
