# Generated by Django 4.2.1 on 2023-05-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_airpollution_aqicategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpollution',
            name='lat',
            field=models.FloatField(verbose_name='lat'),
        ),
        migrations.AlterField(
            model_name='airpollution',
            name='lng',
            field=models.FloatField(verbose_name='lng'),
        ),
    ]
