# Generated by Django 4.2.1 on 2023-05-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_xchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xchoice',
            name='choice',
            field=models.CharField(choices=[('North America', 'North America'), ('Sorth America', 'South America'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('Oceania', 'Oceania')], default='Europe', max_length=20),
        ),
    ]
