# Generated by Django 4.2.1 on 2023-05-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_xchoice_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xChoice',
        ),
    ]
